#!/usr/bin/env bash

function check_toolchain() {

    export TC="$(find ${TOOLCHAIN}/bin -type f -name aarch64-*-gcc)";

	if [[ -f "${TC}" ]]; then
		export CROSS_COMPILE="${TOOLCHAIN}/bin/$(echo ${TC} | awk -F '/' '{print $NF'} |\
sed -e 's/gcc//')";
		echo -e "Using toolchain: $(${CROSS_COMPILE}gcc --version | head -1)";
	else
		echo -e "No suitable toolchain found in ${TOOLCHAIN}";
		exit 1;
	fi
}

export DEVICE=$1;
if [[ -z ${DEVICE} ]]; then
    export DEVICE="mido";
fi

KERNELDIR="${HOME}/kernel"

# These won't change
export SRCDIR="${KERNELDIR}/${DEVICE}";
export OUTDIR="${KERNELDIR}/${DEVICE}/out";
export ANYKERNEL="${KERNELDIR}/anykernel/${DEVICE}";
export ARCH="arm64";
export TOOLCHAIN="${KERNELDIR}/toolchain/SDK26";
export DEFCONFIG="${DEVICE}_defconfig";
export ZIP_DIR="${KERNELDIR}/files/${DEVICE}";
export IMAGE="${OUTDIR}/arch/${ARCH}/boot/Image.gz-dtb";
export VERSION="2.9";
export KBUILD_BUILD_USER="adek";
export KBUILD_BUILD_HOST="ProjectBish-Bot";

export MAKE="make O=${OUTDIR}";

if [[ -z "${JOBS}" ]]; then
    export JOBS="$(nproc --all)";
fi

check_toolchain;

export TCVERSION1="$(${CROSS_COMPILE}gcc --version | head -1 |\
awk -F '(' '{print $2}' | awk '{print tolower($1)}')"
export TCVERSION2="$(${CROSS_COMPILE}gcc --version | head -1 |\
awk -F ')' '{print $2}' | awk '{print tolower($1)}')"
if [[ -z "${NAME}" ]]; then
    export NAME="Stormguard-AOSP_LOS";
fi

export ZIPNAME="${NAME}-${VERSION}-$(date +%Y%m%d-%H%M)-${DEVICE}.zip"
export LOCALVERSION="-AOSP.LOS"
export FINAL_ZIP="${ZIP_DIR}/${ZIPNAME}"

rm -rfv out;

[ ! -d "${ZIP_DIR}" ] && mkdir -pv ${ZIP_DIR}
[ ! -d "${OUTDIR}" ] && mkdir -pv ${OUTDIR}

cd "${SRCDIR}";
rm -fv ${IMAGE};

if [[ "$@" =~ "mrproper" ]]; then
    ${MAKE} mrproper
fi

if [[ "$@" =~ "clean" ]]; then
    ${MAKE} clean
fi

${MAKE} $DEFCONFIG;
START=$(date +"%s");
${MAKE} -j${JOBS};
exitCode="$?";
END=$(date +"%s")
DIFF=$(($END - $START))
echo -e "Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds.";

if [[ ! -f "${IMAGE}" ]]; then
    echo -e "Build failed :P";
    exit 1;
else
    echo -e "Build Succesful!";
fi

echo -e "Copying kernel image";
cp -v "${IMAGE}" "${ANYKERNEL}/";

cd -;
cd ${ANYKERNEL};
zip -r9 ${FINAL_ZIP} *;
cd -;

if [ -f "$FINAL_ZIP" ];
then
echo -e "$ZIPNAME\nzip can be found at $FINAL_ZIP";
echo "=============================================";

git config --global user.name "Adek Maulana"
git config --global user.email "adekm@techdro.id"

cd ${ZIP_DIR};

export UPLOAD="${ZIP_DIR}/AOSP_LOS";
export UPLOAD_ZIP="${UPLOAD}/$ZIPNAME";

mkdir -p AOSP_LOS;

mv $ZIPNAME ${UPLOAD};

git add $UPLOAD_ZIP

echo -e "Wait before pushing...";

git remote rm origin
git remote add origin https://adekmaulana:$GITHUB_API_KEY@github.com/techdro-id/zip.git

git fetch origin master
git pull origin master

git add .

echo -e "Initialize pushing now...";

git commit -m "Stormguard: Travis CI Build #$TRAVIS_BUILD_NUMBER-AOSP/LOS ${DEVICE}"

echo -e "...";

git push -u origin master

echo -e "Pushed...";

git status

echo -e "Pushed succeed";
else
echo -e "Zip Creation Failed =(";
fi # FINAL_ZIP check

exit ${exitCode};
